# General
project: "ELDepth"
random_seed: 26

gpu: 0 #[0,1] or -1 in case don't want to use any gpu

# dataset
dataloader:
  batch_size: 32
  patch_size: [256]
  dim: [256, 256]
  subset: null #pass a int here if you want to use just a subset of the train set
  train_csv: '/workspace/tmp/DIODO_train.csv'
  validation_csv: '/workspace/tmp/DIODO_val.csv'

trainer:
  epochs: 500
  patience: 10
  initial_lr: 2.e-5
  min_lr: 1.e-6
  steps_per_epoch: 100
  validation_steps: 50
  validation_freq: 1
  verbose: 0
  loss: 'loss_SILog' #[custom_loss, mae, mse, charbonnier_loss, loss_SILlog, loss_iRMSE, loss_RMSE]

network:
  type: unet

  UNet:
    null
  SqueezeUNet:
    num_classes: 3
    deconv_ksize: 3
    dropout: 0.5
  XLSR:
    num_gblocks: 4
    nfeat: 32