# General
project: "ELDepth"
random_seed: 26

gpu: 0 #[0,1] or -1 in case don't want to use any gpu

# dataset
dataloader:
  batch_size: 8
  patch_size: [256]
  dim: [256, 256]
  subset: null #pass a int here if you want to use just a subset of the train set
  # aug:
  #   gaussian_noise: False
  #   iso_noise: False
  train: '/datasets/DIODO/train/indoors'
  validation: '/datasets/DIODO/val/indoors'

trainer:
  epochs: 500
  patience: 10
  initial_lr: 2.e-5
  min_lr: 1.e-6
  steps_per_epoch: 100
  validation_steps: 50
  validation_freq: 2
  verbose: 0
  loss: 'custom_loss'

network:
  type: unet

  unet:
    filters: []